FROM eclipse-temurin:21-jdk-alpine AS builder

WORKDIR /app
COPY . .
RUN ./gradlew :coordinator:build

FROM eclipse-temurin:21-jre-alpine

WORKDIR /app
COPY --from=builder /app/coordinator/build/libs/*.jar coordinator.jar

EXPOSE 8080
CMD ["java", "-jar", "coordinator.jar"]
