FROM eclipse-temurin:21-jdk-alpine AS builder

WORKDIR /app
COPY . .
RUN ./gradlew :worker:build

FROM eclipse-temurin:21-jre-alpine

WORKDIR /app
COPY --from=builder /app/worker/build/libs/*.jar worker.jar

CMD ["java", "-jar", "worker.jar"]
